# Generated by Django 5.1.7 on 2025-04-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_order_status_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.CharField(max_length=100),
        ),
    ]
