# Generated by Django 5.1.7 on 2025-04-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_alter_orderitem_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydetail",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_delivery",
                to="mainapp.order",
            ),
        ),
    ]
