# Generated by Django 4.1 on 2025-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_customercart"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercart",
            name="total",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
