# Generated by Django 5.1.7 on 2025-04-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_alter_deliverydetail_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverydetail",
            name="deliverydate",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="deliverydate",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="deliverydate",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescriptiondeliverydetail",
            name="deliverydate",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliveryorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Delivered", "Delivered"),
                    ("Rejected", "Rejected"),
                    ("NoContact", "NoContact"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="medicinerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=100,
            ),
        ),
    ]
