# Generated by Django 4.1 on 2025-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_alter_order_user_ordernew"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercart",
            name="status",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
