# Generated by Django 5.1.7 on 2025-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_deliverydetail_deliverydate_order_deliverydate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydetail",
            name="deliverydate",
            field=models.CharField(default="with in  24 hour", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliverydate",
            field=models.CharField(default="with in 24hour", max_length=100),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="deliverydate",
            field=models.CharField(default="with in 24hours", max_length=100),
        ),
        migrations.AlterField(
            model_name="prescriptiondeliverydetail",
            name="deliverydate",
            field=models.CharField(default="with in 24hours", max_length=100),
        ),
    ]
