# Generated by Django 4.1 on 2025-02-07 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_ordernew_qty_payment_deliverydetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordernew",
            name="cart",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.customercart",
            ),
            preserve_default=False,
        ),
    ]
