# Generated by Django 5.1.7 on 2025-04-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_prescription_deliverydate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverydetail",
            name="deliverydate",
            field=models.CharField(default="with in 48 hour", max_length=100),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="deliverydate",
            field=models.CharField(
                blank=True, default="with in 48hours", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="prescriptiondeliverydetail",
            name="deliverydate",
            field=models.CharField(
                blank=True, default="with in 48hours", max_length=100, null=True
            ),
        ),
    ]
