# Generated by Django 4.1 on 2025-02-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0008_ordernew_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=100)),
                ("predict", models.CharField(max_length=100)),
                ("statue", models.CharField(max_length=100)),
                ("useremail", models.CharField(max_length=100)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Medicinecomment",
                        to="mainapp.medicine",
                    ),
                ),
            ],
        ),
    ]
