# Generated by Django 4.1 on 2025-02-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0009_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("prescription", models.FileField(upload_to="prescriptions/")),
                ("status", models.CharField(max_length=100)),
                ("total_amount", models.CharField(max_length=100)),
                ("remarks", models.TextField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprescription",
                        to="mainapp.user_tbl",
                    ),
                ),
            ],
        ),
    ]
