# Generated by Django 4.1 on 2025-02-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0010_comments_created_at_alter_comments_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="remarks",
            field=models.TextField(default="no remarks", max_length=200),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="status",
            field=models.CharField(default="start", max_length=100),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="total_amount",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.CreateModel(
            name="PrescriptionDeliveryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("houseno", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=100)),
                ("landmark", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.prescription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.user_tbl",
                    ),
                ),
            ],
        ),
    ]
